task 4/src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\Column(type: 'string', length: 200)]
    private $content;

    #[ORM\Column(type: 'datetime')]
    private $date_add;

    #[ORM\Column(type: 'string', length: 255)]
    private $picture;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'books')]
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeInterface
    {
        return $this->date_add;
    }

    public function setDateAdd(\DateTimeInterface $date_add): self
    {
        $this->date_add = $date_add;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

task 4/src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Название'
            ])
            ->add('content', TextType::class, [
                'label' => 'Книга'
            ])
            ->add('picture', TextType::class, [
                'label' => 'Обложка'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

task 4/src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/book')]
class BookController extends AbstractController
{
    //Получение списка всех книг и вывод их на главную страницу
    // Входные данные
    // BookRepository
    // Выходные данные
    // Форма с информацией о всех книгах
    #[Route('/', name: 'app_book_index', methods: ['GET'])]
    public function index(BookRepository $bookRepository): Response
    {
        return $this->render('book/index.html.twig', [
            'books' => $bookRepository->findAll(),
        ]);
    }

    //создание новой книги
    // Входные данные
    // BookRepository
    // Request - нужно для получения информации о залогинившемся пользователе
    // Выходные данные
    // Форма с информацией о конкретной книге
    #[Route('/new', name: 'app_book_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BookRepository $bookRepository): Response
    {
        $book = new Book();
        $user = $this->getUser();
        $book->setDateAdd(new \DateTime('now'));
        $book->setUser($user);
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookRepository->add($book, true);

            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/new.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    //редактировать книгу
    // Входные данные
    // bookRepository
    // book - (объект) конкретная книга, информацию о которой нужно изменить
    // request - нужно для получения информации о залогинившемся пользователе
    // Выходные данные
    // Форма с информацией о конкретной книге, если получилось добавить книгу, или информация о всех книгах пользователя
    #[Route('/{id}/edit', name: 'app_book_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Book $book, BookRepository $bookRepository): Response
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookRepository->add($book, true);

            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/edit.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    //удалить книгу
    // Входные данные
    // bookRepository - см документацию Symfony
    // book - (объект) конкретная книга, которую нужно удалить
    // request - нужно для получения информации о залогинившемся пользователе
    // Выходные данные
    // Редирект на app_book_index
    #[Route('/{id}', name: 'app_book_delete', methods: ['POST'])]
    public function delete(Request $request, Book $book, BookRepository $bookRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $book->getId(), $request->request->get('_token'))) {
            $bookRepository->remove($book, true);
        }

        return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
    }
}

task 4/templates/book/_delete_form.html.twig
<form method="post" action="{{ path('app_book_delete', {'id': book.id}) }}" onsubmit="return confirm('Вы действительно хотите удалить эту книгу??');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn btn-outline-danger">Удалить</button>
</form>

task 4/templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-dark mb-2">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

task 4/templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Book{% endblock %}

{% block body %}
<div class="container">
    <h1>Редактировать книгу</h1>

    {{ include('book/_form.html.twig', {'button_label': 'Изменить'}) }}

    <a href="{{ path('app_book_index') }}"><button type="button" class="btn btn-dark mb-3">На главную</button></a>

    {{ include('book/_delete_form.html.twig') }}
</div>
{% endblock %}

task 4/templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book index{% endblock %}

{% block body %}

<div class="bg-secondary bg-opacity-25 pb-5">
    <div class="container">
        <div class="row row-cols-md-4 g-1 p-2" >

            {% for book in books %}

            <div class="col">
                <div class="card h-100 shadow">
                    <div class="card-header">
                        <img src="{{ book.picture }}" class="card-img-top" alt="..." style="object-fit: picture; object-position: center;height: 27vw;">
                    </div>

                    <div class="card-body">
                        <div>
                            <h5 class="card-title">{{ book.name }}</h5>
                            <small class="text-muted">{{ book.dateAdd ? book.dateAdd|date('Y-m-d H:i:s') : '' }}</small>
                        </div>
                    </div>

                    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start card-footer">

                        <a href="{{ book.content }}" class="col-6 col-md-12 col-xl-6 ml-auto mb-md-1 mb-xl-0">
                            <button type="button" class="btn btn-outline-dark">Читать</button>
                        </a>
                        {% if app.user  and app.user == book.user %}
                            <a href="{{ path('app_book_edit', {'id': book.id}) }}" class="col-6 col-md-12 col-xl-6">
                                <button type="button" class="btn btn-outline-dark">Редактировать</button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>


        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </div>

    </div>
</div>

{% endblock %}

task 4/templates/book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Book{% endblock %}

{% block body %}
<div class="container">
    <h1>Добавить книгу</h1>

    {{ include('book/_form.html.twig') }}

    <a href="{{ path('app_book_index') }}"><button type="button" class="btn btn-dark mb-3">На главную</button></a>

</div>
{% endblock %}

task 4/templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book{% endblock %}

{% block body %}
    <h1>Book</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ book.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ book.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ book.content }}</td>
            </tr>
            <tr>
                <th>Cover</th>
                <td>{{ book.cover }}</td>
            </tr>
            <tr>
                <th>Date_added</th>
                <td>{{ book.dateAdd ? book.dateAdd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_book_index') }}">back to list</a>

    <a href="{{ path('app_book_edit', {'id': book.id}) }}">edit</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}